name: Sync Flow to Flow2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-to-flow2:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Set Commit SHA
        id: vars
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Checkout Flow Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set Git Identity
        run: |
          git config --global user.name "shepherdpraise"
          git config --global user.email "shepherd.praise@yahoo.com"

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git fetch origin
          git submodule foreach git checkout main
          git submodule foreach git pull origin main

      - name: Commit Submodule Updates
        id: commit
        run: |
          git add .
          git diff --cached --quiet && echo "NO_CHANGES=true" >> $GITHUB_ENV || git commit -m "Update submodules for Flow2 sync"

      - name: Skip if no changes
        if: env.NO_CHANGES == 'true'
        run: echo "No changes to sync. Exiting early." && exit 0

      - name: Add Flow2 Remote and Push
        run: |
          git remote add flow2 https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ShepherdPraise/pipelineflow2.git
          git push flow2 HEAD:Flow2-sync-${{ steps.vars.outputs.sha }}

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request in Flow2
        run: |
          gh repo set-default ShepherdPraise/pipelineflow2
          gh pr create \
            --title "Sync Flow to Flow2" \
            --body "Syncs changes from ShepherdPraise/pipelineflow to ShepherdPraise/pipelineflow2, including updated submodules." \
            --base main \
            --head Flow2-sync-${{ steps.vars.outputs.sha }} \
            --label "automated-sync"
