name: Sync Flow to Flow2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-to-flow2:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Set Commit SHA
        id: vars
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Checkout pipelineflow with full history and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set Git Identity
        run: |
          git config --global user.name "shepherdpraise"
          git config --global user.email "shepherd.praise@yahoo.com"

      - name: Update and Sync Submodules
        run: |
          git submodule sync
          git submodule update --init --recursive
          git submodule foreach git fetch origin
          git submodule foreach git checkout main
          git submodule foreach git pull origin main

      - name: Prepare clean sync directory
        run: |
          mkdir -p $RUNNER_TEMP/sync-dir
          rsync -av --exclude='.git' ./ $RUNNER_TEMP/sync-dir/

      - name: Ensure clean clone target
        run: rm -rf $RUNNER_TEMP/pipelineflow2

      - name: Clone pipelineflow2
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ShepherdPraise/pipelineflow2.git $RUNNER_TEMP/pipelineflow2
          test -d $RUNNER_TEMP/pipelineflow2/.git || { echo "❌ .git directory not found in clone target"; exit 1; }

      - name: Copy and commit changes into pipelineflow2
        working-directory: ${{ runner.temp }}/pipelineflow2
        run: |
          git checkout -b Flow2-sync-${{ steps.vars.outputs.sha }}
          rsync -av --delete $RUNNER_TEMP/sync-dir/ ./
          git config user.name "shepherdpraise"
          git config user.email "shepherd.praise@yahoo.com"
          git add .
          git commit -m "Force sync from pipelineflow to pipelineflow2 – SHA ${{ steps.vars.outputs.sha }}" || echo "No changes to commit"
          git push origin Flow2-sync-${{ steps.vars.outputs.sha }}

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Ensure PR label exists in pipelineflow2
        run: |
          gh label create "automated-sync" \
            --repo ShepherdPraise/pipelineflow2 \
            --color "0366d6" \
            --description "PRs created by pipelineflow sync job" || echo "✅ Label already exists"

      - name: Create PR in pipelineflow2
        working-directory: ${{ runner.temp }}/pipelineflow2
        run: |
          gh pr create \
            --repo ShepherdPraise/pipelineflow2 \
            --title "Force Sync Flow to Flow2" \
            --body "Forced sync from pipelineflow. SHA: ${{ steps.vars.outputs.sha }}" \
            --base main \
            --head Flow2-sync-${{ steps.vars.outputs.sha }} \
            --label "automated-sync"
