name: Sync Flow to Flow2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-to-flow2:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Set Commit SHA
        id: vars
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Checkout with full history and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set Git Identity
        run: |
          git config --global user.name "shepherdpraise"
          git config --global user.email "shepherd.praise@yahoo.com"

      - name: Update and Sync Submodules
        run: |
          git submodule sync
          git submodule update --init --recursive
          git submodule foreach git fetch origin
          git submodule foreach git checkout main
          git submodule foreach git pull origin main

      - name: Commit Submodule Updates (no-op allowed)
        run: |
          git add .
          git commit -m "Force sync from Flow to Flow2 – SHA ${{ steps.vars.outputs.sha }}" || echo "No changes to commit – continuing anyway"

      - name: Create Sync Branch
        run: |
          git checkout -b Flow2-sync-${{ steps.vars.outputs.sha }}

      - name: Push to pipelineflow2
        run: |
          git remote add flow2 https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ShepherdPraise/pipelineflow2.git
          git push --force flow2 HEAD:Flow2-sync-${{ steps.vars.outputs.sha }}

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Ensure PR label exists
        run: |
          gh label create "automated-sync" \
            --repo ShepherdPraise/pipelineflow2 \
            --color "0366d6" \
            --description "PRs created by pipelineflow sync job" || echo "✅ Label already exists"

      - name: Create PR in pipelineflow2
        run: |
          gh pr create \
            --repo ShepherdPraise/pipelineflow2 \
            --title "Force Sync Flow to Flow2" \
            --body "Forced sync from pipelineflow. SHA: ${{ steps.vars.outputs.sha }}" \
            --base main \
            --head Flow2-sync-${{ steps.vars.outputs.sha }} \
            --label "automated-sync"
