name: Sync Flow to Flow2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-to-flow2:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Set Commit SHA
        id: vars
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Checkout pipelineflow2 as base
        uses: actions/checkout@v4
        with:
          repository: ShepherdPraise/pipelineflow2
          token: ${{ secrets.PAT_TOKEN }}
          path: pipelineflow2
          fetch-depth: 0
          submodules: recursive

      - name: Add pipelineflow as remote and fetch
        working-directory: pipelineflow2
        run: |
          git remote add source https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ShepherdPraise/pipelineflow.git
          git fetch source

      - name: Merge pipelineflow/main into pipelineflow2/main
        working-directory: pipelineflow2
        run: |
          git checkout main
          git merge source/main --allow-unrelated-histories -m "Merge from pipelineflow into pipelineflow2"

      - name: Sync submodules from source
        working-directory: pipelineflow2
        run: |
          git submodule sync
          git submodule update --init --recursive
          git submodule foreach git fetch origin
          git submodule foreach git checkout main
          git submodule foreach git pull origin main

      - name: Set Git Identity
        working-directory: pipelineflow2
        run: |
          git config user.name "shepherdpraise"
          git config user.email "shepherd.praise@yahoo.com"

      - name: Commit merged changes
        working-directory: pipelineflow2
        run: |
          git add .
          git commit -m "Sync from pipelineflow – SHA ${{ steps.vars.outputs.sha }}" || echo "No changes to commit"

      - name: Create Sync Branch
        working-directory: pipelineflow2
        run: |
          git checkout -b Flow2-merge-${{ steps.vars.outputs.sha }}

      - name: Push to pipelineflow2
        working-directory: pipelineflow2
        run: |
          git push --force origin Flow2-merge-${{ steps.vars.outputs.sha }}

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Ensure PR label exists
        run: |
          gh label create "automated-sync" \
            --repo ShepherdPraise/pipelineflow2 \
            --color "0366d6" \
            --description "PRs created by pipelineflow sync job" || echo "✅ Label already exists"

      - name: Create PR in pipelineflow2
        run: |
          gh pr create \
            --repo ShepherdPraise/pipelineflow2 \
            --title "Merge pipelineflow into pipelineflow2" \
            --body "This PR merges the latest from pipelineflow (SHA: ${{ steps.vars.outputs.sha }}) into pipelineflow2" \
            --base main \
            --head Flow2-merge-${{ steps.vars.outputs.sha }} \
            --label "automated-sync"
